### ISSUE TITLE
Only downloads 3kb for each file if located on https://media-files9.bunkr.ru/

### ISSUE THREAD

**Issue by trikki69** [PaaaulZ/CyberdropBunkrDownloader#10]
As title suggests, downloads working fine unless the files to be downloaded are on https://media-files9.bunkr.ru/
They appear to download and get added to the "already_downloaded.txt" file no error is displayed.
Looking at the downloaded files, they're all 3kb in size, any files NOT on https://media-files9.bunkr.ru/ download without issue.

**Comment by PaaaulZ** [comment]
They are having problems with some servers, included the main one for video streaming. Check on status.bunkr.ru

I think it may be related to that but I'll check it as soon as I can

**Comment by trikki69** [comment]
Thanks you :)
I think you're right - although I'm sure I've checked that videos will stream before I try and download again... just tried again now and the vid is just black screen for 25 secs... makes sense now.

Thanks for creating this - great work :)

**Comment by trikki69** [comment]
Jjust checked and pretty much all files from bunkr.ru/a/N9U2y9UL stream fine but when I try to download them, every file downloads as 3kb with no contents.

**Comment by PaaaulZ** [comment]
Fixed. I forgot to change a line when they changed domain to bunkr.ru
Thank you for the issue and example link
