### ISSUE TITLE
Issue on Health Checker

### ISSUE THREAD

**Issue by Msameim181** [PaaaulZ/CyberdropBunkrDownloader#13]
Regarding this marge and the commit [f50973934c5a6096c501c0f4e299fb455c953cd5], this checker won't allow downloading even if all like are downloadable from an active server. It is blocking downloads because one or two servers may be down.

It is better to check each link, if it has a problem will notify the user.

**Comment by PaaaulZ** [comment]
I was working on an additional check and I implemented something for this too
