### ISSUE TITLE
hello i got issue..

### ISSUE THREAD

**Issue by FTLClass** [PaaaulZ/CyberdropBunkrDownloader#15]
I use docker ubuntu
i was use this code, it was great
but i use today, it doesn't work
plz help me. 
best regards

Traceback (most recent call last):                                              
  File "/cyber/dump.py", line 165, in <module>                                  
    get_items_list(args.u, args.e, args.s, args.i, args.w, args.p, args.cfs, arg
s.css)                                                                          
  File "/cyber/dump.py", line 43, in get_items_list                             
    extension = get_url_data(item['url'])['extension']                          
TypeError: string indices must be integers

**Comment by trikki69** [comment]
I think 'bunkr.su' needs adding to the URL list... it seems bunkr keep changing or adding tlds.

**Comment by PaaaulZ** [comment]
They changed how the website works, I made a temporary update but I'll have to test it more

**Comment by AceidicDawn** [comment]
Hi i'm still getting this error quite often, not sure how to proceed.

**Comment by PaaaulZ** [comment]
Can you open another issue with an example link and the full error?
