### ISSUE TITLE
Error when using Cyberdrop link (Network Issue?)

### ISSUE THREAD

**Issue by jleseane23** [PaaaulZ/CyberdropBunkrDownloader#16]
The files are on FS01, FS02, & FS03 and I think they are all down. Just wanted to be sure this error was related to the site being down and nothing on my end. I tried using the css argument but I'm getting the same error

  File "/home/path/git/CyberdropBunkrDownloader/dump.py", line 158, in <module>
    get_items_list(args.u, args.e, args.w, args.p, args.css)
  File "/home/path/git/CyberdropBunkrDownloader/dump.py", line 39, in get_items_list
    extension = get_url_data(item['url'])['extension']
TypeError: string indices must be integers

**Comment by PaaaulZ** [comment]
Fixed with latest commit
