### ISSUE TITLE
Error when trying downloading from bunkr

### ISSUE THREAD

**Issue by onupirat** [PaaaulZ/CyberdropBunkrDownloader#19]
![Screenshot_21](https://user-images.githubusercontent.com/57112817/232106882-8d027515-8788-467d-a430-ec4b428b24df.png)

**Comment by PaaaulZ** [comment]
They implemented something like DDOSGuard that is blocking request from bots. I currently have no idea how to bypass it, might have to do some cookie magic but I can't tell how much time I need since it's not easy to bypass

**Comment by onupirat** [comment]
Well that explains why cyberdrop-dl, the other program that i tried, doesn't download all the files, and sometimes doesn't download at all. Yet it still downloads sometimes somehow, so probably there is a way to make your program work.
