### ISSUE TITLE
don't support this file support

### ISSUE THREAD

**Issue by 1581-netizen** [PaaaulZ/CyberdropBunkrDownloader#2]
The downloaded files have a file format that does not allow the opening of the file itself (both video and image).

![image](https://user-images.githubusercontent.com/75811903/182134070-94745796-970a-4ace-87ad-389684221110.png)

**Comment by PaaaulZ** [comment]
Can you provide a link to the album so I can test it? 
Thank you

**Comment by fire2368** [comment]
Same issue here, all the files download are really small in size and are corrupt/no content
