### ISSUE TITLE
TypeError: string indices must be integers, not 'str'

### ISSUE THREAD

**Issue by AceidicDawn** [PaaaulZ/CyberdropBunkrDownloader#26]
When i try to download albums, i get this error. 

Traceback (most recent call last):
  File "Q:\dump\dump.py", line 182, in <module>
    get_items_list(args.u, args.e, args.w, args.p)
  File "Q:\dump\dump.py", line 53, in get_items_list
    extension = get_url_data(item['url'])['extension']
                             ~~~~^^^^^^^
TypeError: string indices must be integers, not 'str'

the link i used for this error message:  https://bunkrr.su/a/6a3MVt1b

however, it happens with a majority of links i try.

**Comment by PaaaulZ** [comment]
Can you try redownloading the latest version? That link is downloading fine on my end and the error is a bit weird

**Comment by AceidicDawn** [comment]
no luck sorry, i tried redownloading the app, and reinstalling python and packages, no luck.

i had no issue for a while and then a week or so ago it just started doing this.

**Comment by PaaaulZ** [comment]
I think for some reason you get an http error for some links, maybe you get blocked by ddosguard. 
Please download this new version and try again, it should not crash anymore but log the urls that it fails to download

Let me know so I can close this, thanks

**Comment by AceidicDawn** [comment]
The fix is working as inteded it seems, as i now get a HTTP error message. So while i still can't download, now atleast i know the problem.

Thanks for your time and effort.

**Comment by PaaaulZ** [comment]
Just out of curiosity what is the error the you get?

**Comment by AceidicDawn** [comment]
HTTP error 403 getting real url for /i/DjXFA3OT0IotI
                [-] Unable to find a download link for None

and then it repeats for the files in the album, with the last bit of the first line changing each time

**Comment by PaaaulZ** [comment]
I think it may be ddosguard then, very weird that doesn't happen to me. I will keep testing

**Comment by AceidicDawn** [comment]
I have been downloading a lot the last week or so, so wouldn't be surprised if it sniped me. Thanks again
