### ISSUE TITLE
it only downloaded 4 videos then stopped 

### ISSUE THREAD

**Issue by ijustmadethislol** [PaaaulZ/CyberdropBunkrDownloader#3]
like i said in the title it was workign and downloading then stopped it at 4 videos 
i was downloading this album https://bunkr.is/a/f0CrHLge
![image](https://user-images.githubusercontent.com/111335870/184802636-4abe37e3-1024-47df-ab25-ae1d65a92ae2.png)

**Comment by PaaaulZ** [comment]
The album is downloading fine for me, maybe bunkr was slow at that time. Did you get an error or the program just showed "downloading"?

**Comment by ijustmadethislol** [comment]
it just showed downloading for like 20 mins

**Comment by ijustmadethislol** [comment]
and it was paused or frozen
