### ISSUE TITLE
Get 403 error 

### ISSUE THREAD

**Issue by tommaso-ascani** [PaaaulZ/CyberdropBunkrDownloader#32]
I'm getting this error:

[-] HTTP error 403 getting real url for url...
                [-] Unable to find a download link

I think it's caused by ddos guard, tried some fix with user-agent and some, but no fix.

**Comment by PaaaulZ** [comment]
Yes 403 errors are 90% ddos guard blocking, googlebot user agent used to bypass it but now doesn't work anymore
I don't know alternative methods to bypass and I don't think I will ever implement it, I don't want to piss the webmaster off, unfortunately I have no solution to offer :(
