### ISSUE TITLE
Can't download from Bunkr

### ISSUE THREAD

**Issue by glsmith86** [PaaaulZ/CyberdropBunkrDownloader#33]
$ bunkr https://bunkrr.ru/a/W6ww9f
Traceback (most recent call last):
  File "/home/glsmith/dump.py", line 182, in <module>
    get_items_list(args.u, args.e, args.w, args.p)
  File "/home/glsmith/dump.py", line 41, in get_items_list
    album_name = remove_illegal_chars(soup.find('h1', {'id': 'title'}).text)
AttributeError: 'NoneType' object has no attribute 'text'

Bunkr is a sh file. It contains: python3 /home/*****/dump.py -u $1

**Comment by PaaaulZ** [comment]
Hi, looks like that album does not exist.
Wrong link?

**Comment by glsmith86** [comment]
Album exists, I copied the link from browser.

**Comment by glsmith86** [comment]
Another trying

bunkr https://bunkrr.ru/a/VNlYHhrD
Traceback (most recent call last):
  File "/home/glsmith/dump.py", line 182, in <module>
    get_items_list(args.u, args.e, args.w, args.p)
  File "/home/glsmith/dump.py", line 41, in get_items_list
    album_name = remove_illegal_chars(soup.find('h1', {'id': 'title'}).text)
AttributeError: 'NoneType' object has no attribute 'text'

**Comment by PaaaulZ** [comment]
If I copy the url you posted I get error 404 and W6ww9f seems like a very short id for a bunkr album.

The album does not seem exist or it's private, I don't know which but I can't access that album

**Comment by PaaaulZ** [comment]
Ok this new link works, seems like they updated the domain.
Download this new version and try again please

**Comment by glsmith86** [comment]
Another trying

bunkr https://bunkrr.ru/a/VNlYHhrD
Traceback (most recent call last):
File "/home/glsmith/dump.py", line 182, in
get_items_list(args.u, args.e, args.w, args.p)
File "/home/glsmith/dump.py", line 41, in get_items_list
album_name = remove_illegal_chars(soup.find('h1', {'id': 'title'}).text)
AttributeError: 'NoneType' object has no attribute 'text'
