### ISSUE TITLE
bunkr downloads

### ISSUE THREAD

**Issue by geolaw** [PaaaulZ/CyberdropBunkrDownloader#4]
Only found this repo looking for something to download from bunkr - which out of the box seemed to be broken.

I've managed to get it working by adjusting how it pulls the file list out of the json, e.g. 
         files = json_data["props"]["pageProps"]["album"]["files"]

as well as extractng the album name and appending that as part of the 'save' directory.

I am not sure if my mods are going to be specific to bunkr URLs or what?!
If you have a couple other URLS that should work - I can tweak my changes so they're only applicable for bunkr and I can fork and contribute those changes back up to you.

**Comment by geolaw** [comment]
note - bunkr downloads were not working before my changes :) 

I also had to change the URL - looking at the download URL from firefox, this entry :  
{'name': 'dmn19badft-du30LYKF-c8czUgiD.mp4', 'size': '331114477', 'timestamp': 1659197068, 'cdn': 'https://cdn3.bunkr.is', 'i': 'https://i3.bunkr.is'}

was on media-files3.bunkr.is -- 
[+] Downloading https://media-files3.bunkr.is/dmn19badfck-4jDkCMxA-xAIe08uy.mp4

Not sure if this is going to be the same for all or if the '3' in the json output determines the download url ?! 

was also going to add a -s 12345  parameter to only download files larger than 12345

**Comment by PaaaulZ** [comment]
Fixed downloader and added suggested improvements.
Thank you

**Comment by oorzkws** [comment]
Thanks for the detailed description geolaw, this helped me solve the issue I was having. MP4 from cdn*.bunkr.is would come as 3kb files because it was being served as a preview page.

I'm not super familiar with python but this is what I changed to fix the downloads:
```python
item_urls = [f"{file['cdn'].replace('/cdn','/media-files')}/{file['name']}" for file in files if int(file['size']) > (min_file_size * 1000)]
```
